export * from './glpi-asset.model';
export * from './computer.model';
export * from './monitor.model';
export * from './printer.model';
export * from './phone.model';
export * from './peripheral.model';
export * from './network-equipment.model';
export * from './enclosure.model';
export * from './pdu.model';
export * from './passive-dc-equipment.model';
export * from './rack.model';
export * from './cable.model';
export * from './appliance.model';
export * from './certificate.model';
export * from './socket.model';
export * from './software.model';
export * from './software-license.model';
export type { AnyAsset } from './any-asset.model';
