export const erasableEndpoints: readonly string[] = [
  '/supply_order_receipt_histories',
  '/supply_order_histories',
  '/supply_order_details',
  '/supply_orders',
  '/warehouse_product_locations',
  '/stock_movements',
  '/stocks',
  '/warehouses',
  '/customer_messages',
  '/messages',
  '/customer_threads',
  '/order_cart_rules',
  '/order_payments',
  '/order_slip',
  '/order_invoices',
  '/order_carriers',
  '/order_histories',
  '/customizations',
  '/order_details',
  '/deliveries',
  '/orders',
  '/carts',
  '/specific_prices',
  '/specific_price_rules',
  '/cart_rules',
  '/product_suppliers',
  '/product_customization_fields',
  '/combinations',
  '/product_feature_values',
  '/product_features',
  '/product_option_values',
  '/product_options',
  '/tags',
  '/images',
  '/attachments',
  '/products',
  '/categories',
  '/manufacturers',
  '/suppliers',
  '/content_management_system',
  '/addresses',
  '/guests',
  '/customers',
] as const;

export const nonErasableEndpoints: readonly string[] = [
  '/carriers',
  '/configurations',
  '/contacts',
  '/countries',
  '/currencies',
  '/employees',
  '/groups',
  '/image_types',
  '/languages',
  '/order_states',
  '/price_ranges',
  '/shop_groups',
  '/shop_urls',
  '/shops',
  '/states',
  '/stock_movement_reasons',
  '/stores',
  '/supply_order_states',
  '/tax_rule_groups',
  '/tax_rules',
  '/taxes',
  '/translated_configurations',
  '/weight_ranges',
  '/zones',
] as const;

export interface SpecialHandlingConfig {
  action: 'delete_filtered' | 'put_quantity_zero';
  note: string;
  filter?: string;
}

export const specialHandlingEndpoints: Readonly<Record<string, SpecialHandlingConfig>> = {
  '/categories': {
    action: 'delete_filtered',
    filter: 'id=![1|2]',
    note: 'Keep Root (id=1) and Home (id=2) — hardcoded in PrestaShop core',
  },
  '/addresses': {
    action: 'delete_filtered',
    filter: 'id_customer=![0]',
    note: 'Keep system addresses (shops, warehouses) where id_customer=0',
  },
  '/stock_availables': {
    action: 'put_quantity_zero',
    note: 'NEVER DELETE — causes front-office crash on every product page. Use PUT to set quantity=0',
  },
};
